### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by ryandesign** [lynx/lynx#1]
Naming your project "lynx" is unfortunate, since there is an [existing software project called lynx](http://lynx.invisible-island.net). People looking for the source code of that project might inadvertently end up finding your project instead, as I just did.

**Comment by ovr** [comment]
Hey! I didnt known that, there is `Lynx` browser, but

- There are 773 repositories on GitHub with `Lynx` name https://github.com/search?utf8=%E2%9C%93&q=lynx&type=
- Lynx is a simple word from English dictionary, name of an animal
- Lynx is not a registered trademark

Thank you, but I am going to close an issue, feel free to comment?
