### ISSUE TITLE
Unable to join testnet. Peers eventually get banned.

### ISSUE THREAD

**Issue by fogoat** [lynx/lynx#2]
I've already tried this in the `lynx.conf`:

```css
testnet=1
addnode=test00.getlynx.io
addnode=test01.getlynx.io
addnode=test02.getlynx.io
addnode=test03.getlynx.io
```

I get peers, but they eventually get banned. I don't know why this happening. I've been struggling with this for weeks and I'm not sure what else I can try to join testnet.

I also don't have any tLYNX so I don't know how I'd participate in mining if I need 1k tLYNX.

![image](https://user-images.githubusercontent.com/6989799/51886594-4e024d00-2345-11e9-8b4b-48e831b0908a.png)

**Comment by ovr** [comment]
Hey!

This project is not related, you should go to https://github.com/getlynx/Lynx

Thanks
